[DEFAULT]
# On sw-hot use 172.30.201.248 — on sw-cold use 172.30.201.249
bind_ip = 0.0.0.0
bind_port = 6200
workers = 2
user = swift
swift_dir = /etc/swift
devices = /srv/node
mount_check = false
disable_fallocate = true
log_facility = LOG_LOCAL2

[pipeline:main]
pipeline = healthcheck recon object-server

[app:object-server]
use = egg:swift#object

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:recon]
use = egg:swift#recon

[object-replicator]

[object-updater]

[object-auditor]
