[DEFAULT]
bind_ip = 172.30.201.247
bind_port = 8080
workers = 2
user = swift
log_facility = LOG_LOCAL1

[pipeline:main]
# TempAuth for the lab (no Keystone).
pipeline = catch_errors gatekeeper healthcheck proxy-logging cache tempauth proxy-logging proxy-server

[app:proxy-server]
use = egg:swift#proxy
allow_account_management = true
account_autocreate = true

[filter:tempauth]
use = egg:swift#tempauth
user_admin_admin = admin .admin .reseller_admin
user_test_tester = testing .admin
user_test2_tester2 = testing2 .admin
user_test_tester3 = testing3

[filter:cache]
use = egg:swift#memcache
memcache_servers = 172.30.201.247:11211

[filter:catch_errors]
use = egg:swift#catch_errors

[filter:gatekeeper]
use = egg:swift#gatekeeper

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:proxy-logging]
use = egg:swift#proxy_logging
