[swift-hash]
# MUST be identical on sw-proxy, sw-hot, and sw-cold.
# Generate once on laptop:  openssl rand -hex 10
swift_hash_path_suffix = CHANGEME_SUFFIX
swift_hash_path_prefix = CHANGEME_PREFIX

[storage-policy:0]
name = hot
default = yes

[storage-policy:1]
name = cold
